name: CI Workflow Main
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_call:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Maven Compile/Test
        run: mvn --activate-profiles prod test
  build-and-package:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Maven Compile/Package
        run: mvn --activate-profiles prod -DskipTests package
#mvn --activate-profiles prod package
#mvn test
#mvn package -DskipTests
